### ISSUE TITLE
example needed

### ISSUE THREAD

**Issue by olivierlambert** [vatesfr/xo-import-servers-csv#7]
We need a sample CSV file

**Comment by patelnet** [comment]
When importing, using a CSV with first line as the header, the import does not work correctly.  it actually adds the header to the sever list, and puts the label in the host section
![capture 3](https://user-images.githubusercontent.com/38188385/38470309-b0093ad6-3b15-11e8-8389-8c89e4d28c28.PNG)


![capture1](https://user-images.githubusercontent.com/38188385/38470278-43bd4f3e-3b15-11e8-8d6b-36b33d8b7d9e.PNG)
![capture2](https://user-images.githubusercontent.com/38188385/38470280-45c3ee00-3b15-11e8-98b6-b694e335b379.PNG)

**Comment by julien-f** [comment]
@patelnet Support for `label` field added in https://github.com/vatesfr/xo-import-servers-csv/commit/39a84a1ac0a46847ef7869179e3f99b02a57adfa

Documentation added in https://github.com/vatesfr/xo-import-servers-csv/commit/5cca58f2b3cfa838c0974c52dbdc4229752cd1bd.
